# Generated by Django 5.1.2 on 2024-10-20 18:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bank_cash',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Cash', 'Cash')], default='Cash', max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0.09, max_digits=5),
        ),
        migrations.AddField(
            model_name='expense',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='expense',
            name='kgst',
            field=models.DecimalField(decimal_places=2, default=0.09, max_digits=5),
        ),
        migrations.AddField(
            model_name='expense',
            name='tds',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='expense',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='party',
            field=models.CharField(max_length=100),
        ),
    ]
