# Generated by Django 5.1.2 on 2024-10-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_expense_bank_cash_expense_cgst_expense_igst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='invoice_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
