# Generated by Django 5.1.2 on 2024-10-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_expense_invoice_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='total',
        ),
        migrations.AlterField(
            model_name='expense',
            name='invoice_no',
            field=models.CharField(max_length=50),
        ),
    ]
