# Generated by Django 5.1.2 on 2024-10-21 08:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_expense_total_alter_expense_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
