# Generated by Django 5.1.2 on 2024-10-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_expense_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='expense',
            name='kgst',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=5),
        ),
    ]
