# Generated by Django 5.1.2 on 2024-10-21 14:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_expense_amount_alter_expense_cgst_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('gst_applied', models.BooleanField(default=False)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('description', models.CharField(choices=[('Resource Utilization Charge', 'Resource Utilization Charge'), ('Resource Recruitment Charge', 'Resource Recruitment Charge')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('gst_applied', models.BooleanField(default=False)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('name', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('description', models.CharField(default='Fees', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
