# Generated by Django 5.1.2 on 2024-10-22 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_expense_cgst_alter_expense_igst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='gst_applied',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='gst_applied',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='number',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='total',
        ),
        migrations.AddField(
            model_name='invoice',
            name='gst',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='aytech_ir000', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='gst',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(default='aytech_ir000', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='batch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
