# Generated by Django 5.1.2 on 2024-10-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_invoice_gst_applied_remove_invoice_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
