# Generated by Django 5.1.2 on 2025-03-03 07:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_invoice_delete_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='bank_cash',
            field=models.CharField(default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='invoice_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='kgst',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tds',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
